spring:
  application:
  name: taskmanager
  datasource:
    url: jdbc:oracle:thin:${ORACLE_DB_CONNECTION_STRING}
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
  
  # Server settings  
server:
  port: 9090
  servlet:
    context-path: "/api"
  
  # Logging  
logging:
  level:
    root: "INFO"
  file:
    name: "logs/application.log"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %p %c{36} - %m%n"
  
  # Custom properties  
app:
  name: "Task Manager App"
  version: "1.0"

jwt:
  secret: ${JWT_SECRET}

frontend:
  location: ${FRONTEND_LOCATION}