spring:
  application:
  name: taskmanager
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: # no password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Server settings
server:
  port: 9090
  servlet:
    context-path: "/api"

  # Logging
logging:
  level:
    root: "DEBUG"
  file:
    name: "logs/application.log"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %p %c{36} - %m%n"

  # Custom properties
app:
  name: "Task Manager App"
  version: "1.0"

jwt:
  secret: "Test"

domain:
  name: "http://localhost:9090"