# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD w/ Maven, Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean verify

  docker-build-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

    - name: Build, tag, and push
      run: |
        docker build -t "${{ secrets.DOCKER_HUB_USER }}"/taskmanager:latest .
        docker push "${{ secrets.DOCKER_HUB_USER }}"/taskmanager:latest

  azure-app-service:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
    - uses:  azure/webapps-deploy@v2
      with:
        app-name: auwate-taskmanager
        publish-profile: "${{ secrets.AZURE_PUBLISH_PROFILE }}"
        images: 'docker.io/${{ secrets.DOCKER_HUB_USER }}/taskmanager:latest'